name: test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: check out
        uses: actions/checkout@v2
      - name: test
        run: go test -count=1 -p=1 ./... -v
